GET http://localhost:8080/api/wanaka/profile/1111111111 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDI1NTEyOTYsInVzZXIiOiJhcGktZGV2In0.xISX7zlmRTUXjtuhdPiuFyxE8WNKYcrGqd7rjsW6kpo